# Site settings
title: Christopher Nilghe | Web & iOS Full-stack Developer
email: chris@nilghe.com
description: > # this means to ignore newlines until "baseurl:"
  Web & iOS Full-stack Developer living in Tokyo Japan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nilghe.com" # the base hostname & protocol for your site
twitter_username: burninlover
github_username:  nilghe
gitlab_username:  nilghe
linkedin_username: chrisnilghe

# Build settings
markdown: kramdown

exclude: [bower_components]
sass:
  style: compressed
